# Generated by Django 4.2 on 2023-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_createblog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
