# Generated by Django 4.2 on 2023-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contact_remove_createblog_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added', '-date_update']},
        ),
        migrations.AlterModelOptions(
            name='createblog',
            options={'ordering': ['-date_added', '-date_update']},
        ),
        migrations.AlterField(
            model_name='createblog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
